# termail example configuration
[termail]
cli = false
default_backend = "greenmail"
email_fetch_count = 100
editor = "code"   # "vim" or "code" for VSCode
plugins = [] # plugins are not case-sensitive

[backends.greenmail]
auth_credentials = { username = "user1@example.com", password = "password123"}
host = "127.0.0.1"
port = 1993
ssl = true
maildir_path = "../Maildir/Greenmail"

[backends.gmail]
host = "imap.gmail.com"
port = 993
ssl = true
oauth2_client_secret_file = "./client_secret.json"
filter_labels = ["CATEGORY_FORUMS", "CATEGORY_UPDATES", "CATEGORY_PERSONAL", "CATEGORY_PROMOTIONS", "CATEGORY_SOCIAL", "UNREAD", "YELLOW_STAR", "CHAT"]
maildir_path = "../Maildir/Gmail"
